name: CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  run-app-ci:
    uses: seb5594/hass-workflows/.github/workflows/engine-app-ci.yml@main
    with:
      app_name: rsync-local
