name: Publish GHCR Release Image

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  run-release:
    uses: seb5594/hass-workflows/.github/workflows/engine-app-release.yml@main
    with:
      app_name: rsync-local
      target_repo: seb5594/Home-Assistant-Apps
    secrets:
      PAT_TOKEN: ${{ secrets.ORCHESTRATION_PAT }}
